---
title: "Cho's life ain't easy"
date: 2021-04-03
---
theme: minima
title: "Cho Cho Land"
author: GitHub User Cho
email: guswind8@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  lets talk about life.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
